import { v4 as uuidv4 } from "uuid";

const categoryObj = [
    {
        id: 1,
        image1: "https://imgur.com/5tBC66q.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "darvozalar",
        name_en: "gates",
        name_ru: "ворота",
        category: 1,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 2,
        image1: "https://imgur.com/CcW3GYi.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "darvozalar",
        name_en: "gates",
        name_ru: "ворота",
        category: 1,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 3,
        image1: "https://imgur.com/OlDIwGY.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "darvozalar",
        name_en: "gates",
        name_ru: "ворота",
        category: 1,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 4,
        image1: "https://imgur.com/8XPGkz1.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "darvozalar",
        name_en: "gates",
        name_ru: "ворота",
        category: 1,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 5,
        image1: "https://imgur.com/5tBC66q.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "darvozalar",
        name_en: "gates",
        name_ru: "ворота",
        category: 1,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 6,
        image1: "https://imgur.com/CcW3GYi.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "darvozalar",
        name_en: "gates",
        name_ru: "ворота",
        category: 1,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 7,
        image1: "https://imgur.com/OlDIwGY.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "darvozalar",
        name_en: "gates",
        name_ru: "ворота",
        category: 1,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 8,
        image1: "https://imgur.com/8XPGkz1.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "darvozalar",
        name_en: "gates",
        name_ru: "ворота",
        category: 1,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 9,
        image1: "https://imgur.com/Drky2dS.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "eshiklar",
        name_en: "doors",
        name_ru: "двери",
        category: 2,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 10,
        image1: "https://imgur.com/CcW3GYi.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "eshiklar",
        name_en: "doors",
        name_ru: "двери",
        category: 2,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 11,
        image1: "https://imgur.com/OlDIwGY.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "eshiklar",
        name_en: "doors",
        name_ru: "двери",
        category: 2,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 12,
        image1: "https://imgur.com/8XPGkz1.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "eshiklar",
        name_en: "doors",
        name_ru: "двери",
        category: 2,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 13,
        image1: "https://imgur.com/5tBC66q.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "eshiklar",
        name_en: "doors",
        name_ru: "двери",
        category: 2,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 14,
        image1: "https://imgur.com/CcW3GYi.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "eshiklar",
        name_en: "doors",
        name_ru: "двери",
        category: 2,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 15,
        image1: "https://imgur.com/OlDIwGY.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "eshiklar",
        name_en: "doors",
        name_ru: "двери",
        category: 2,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 16,
        image1: "https://imgur.com/8XPGkz1.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "eshiklar",
        name_en: "doors",
        name_ru: "двери",
        category: 2,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 17,
        image1: "https://imgur.com/LsyGWwH.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "panjara",
        name_en: "railing",
        name_ru: "перила",
        category: 3,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 18,
        image1: "https://imgur.com/CcW3GYi.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "panjara",
        name_en: "railing",
        name_ru: "перила",
        category: 3,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 19,
        image1: "https://imgur.com/OlDIwGY.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "panjara",
        name_en: "railing",
        name_ru: "перила",
        category: 3,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 20,
        image1: "https://imgur.com/8XPGkz1.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "panjara",
        name_en: "railing",
        name_ru: "перила",
        category: 3,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 21,
        image1: "https://imgur.com/5tBC66q.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "panjara",
        name_en: "railing",
        name_ru: "перила",
        category: 3,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 22,
        image1: "https://imgur.com/CcW3GYi.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "panjara",
        name_en: "railing",
        name_ru: "перила",
        category: 3,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 23,
        image1: "https://imgur.com/OlDIwGY.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "panjara",
        name_en: "railing",
        name_ru: "перила",
        category: 3,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 24,
        image1: "https://imgur.com/8XPGkz1.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "panjara",
        name_en: "railing",
        name_ru: "перила",
        category: 3,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 25,
        image1: "https://static01.nyt.com/images/2020/05/24/business/24VIRUS-HHS-01/merlin_172758585_978f047a-219b-48ad-84cc-f482ec28eb3f-superJumbo.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "to'siqlar",
        name_en: "fences",
        name_ru: "заборы",
        category: 4,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 26,
        image1: "https://imgur.com/CcW3GYi.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "to'siqlar",
        name_en: "fences",
        name_ru: "заборы",
        category: 4,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 27,
        image1: "https://imgur.com/OlDIwGY.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "to'siqlar",
        name_en: "fences",
        name_ru: "заборы",
        category: 4,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 28,
        image1: "https://imgur.com/8XPGkz1.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "to'siqlar",
        name_en: "fences",
        name_ru: "заборы",
        category: 4,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 29,
        image1: "https://imgur.com/5tBC66q.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "to'siqlar",
        name_en: "fences",
        name_ru: "заборы",
        category: 4,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 30,
        image1: "https://imgur.com/CcW3GYi.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "to'siqlar",
        name_en: "fences",
        name_ru: "заборы",
        category: 4,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 31,
        image1: "https://imgur.com/OlDIwGY.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "to'siqlar",
        name_en: "fences",
        name_ru: "заборы",
        category: 4,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
    {
        id: 32,
        image1: "https://imgur.com/8XPGkz1.jpg",
        image2: "https://imgur.com/5tBC66q.jpg",
        image3: "https://imgur.com/5tBC66q.jpg",
        name_uz: "to'siqlar",
        name_en: "fences",
        name_ru: "заборы",
        category: 4,
        description_en: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_ru: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
        description_uz: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    },
]

export default categoryObj;